<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diagnostic" nsURI="http://admitto.unum/models/diagnostic" nsPrefix="hdm">
  <eClassifiers xsi:type="ecore:EClass" name="Name" abstract="true" interface="true">
    <eOperations name="isSimpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check if this Name represents a simple name.&#xA;&#xA;@return  true iff the class implementation represents a simple (nonqualified) name.  The implemenataton class should not be both a SimpleName and QualifiedName."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check if this Name is a qualified name.&#xA;&#xA;@return true iff the class implemenation represents a Qualified Name.  The implemenataton class should not be both a SimpleName and QualifiedName."/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleName" eSuperTypes="#//Name">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedName" eSuperTypes="#//Name">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//SimpleName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" eType="#//QualifiedName"
        eOpposite="#//QualifiedName/qualifiednameeOpposite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiednameeOpposite"
        eType="#//QualifiedName" eOpposite="#//QualifiedName/qualifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagnosticCategory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionName" lowerBound="1"
        eType="#//SimpleName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categoryName" lowerBound="1"
        eType="#//SimpleName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificity" eType="#//QualifiedName"/>
  </eClassifiers>
</ecore:EPackage>
